language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

after_success:
  - ./gradlew jacocoRootReport coveralls

before_deploy:
  - zip -r caru-web *
  - mkdir -p deploy
  - mv caru-web.zip deploy/caru-web.zip
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: caru-deploy # 6-3-3에서 생성한 S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    local_dir: deploy
    wait-until-deployed: true
    on:
      repo: rudeo512/caru
      branch: master
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: caru-deploy # S3 버킷
    key: caru-web.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip
    application: caru # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: caru # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: rudeo512/caru
      branch: master

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
